=== MPDL/INGe/cone/src/main/resources/models.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:model="http://purl.org/escidoc/metadata/profiles/0.1/model"  elementFormDefault="qualified">

    <xs:element name="models">
    	<xs:complexType>
    		<xs:sequence minOccurs="1" maxOccurs="1">
    			<xs:element name="model" maxOccurs="unbounded">
    				<xs:complexType>
    					<xs:sequence>
    						<xs:element name="name" type="xs:NCName"/>
    						<xs:element name="aliases">
    							<xs:complexType>
    								<xs:sequence>
    									<xs:element name="alias" minOccurs="1" maxOccurs="unbounded" type="xs:NCName"/>
    								</xs:sequence>
    							</xs:complexType>
    						</xs:element>
    						<xs:element name="description" minOccurs="0" type="xs:string"/>
    						<xs:element name="open" minOccurs="0" type="xs:boolean" default="true"/>
    						<xs:element name="rdf-about-tag" minOccurs="0" type="xs:QName" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" default="rdf:Description"/>
    						
    						<xs:element name="primary-identifier" minOccurs="1" maxOccurs="1">
    							<xs:complexType>
	    							<xs:simpleContent>
	    								<xs:extension base="xs:anyURI">
	    									<xs:attribute name="control" type="xs:boolean" default="true"/>
	    									<xs:attribute name="generate-cone-id" type="xs:boolean" default="true"/>
	    									<xs:attribute name="identifier-prefix" type="xs:anyURI"/>
	    									<xs:attribute name="subject-prefix" type="xs:anyURI"/>
	    								</xs:extension>
	    							</xs:simpleContent>
    								
    							</xs:complexType>
    						</xs:element>
    						<xs:element name="predicates">
    							<xs:complexType>
    								<xs:sequence>
    									<xs:element name="predicate" type="PredicateType" minOccurs="1" maxOccurs="unbounded"/>
    								</xs:sequence>
    							</xs:complexType>
    						</xs:element>
    						<xs:element name="results" minOccurs="1" maxOccurs="1">
    							<xs:complexType>
    								<xs:sequence>
    									<xs:element name="result" minOccurs="1" maxOccurs="unbounded">
    										<xs:complexType>
			    								<xs:sequence>
			    									<xs:element name="type" minOccurs="0" maxOccurs="1" type="xs:string"/>
			    									<xs:element name="result-pattern" minOccurs="1" maxOccurs="1" type="xs:string"/>
			    									<xs:element name="sort-pattern" minOccurs="0" maxOccurs="1" type="xs:string"/>
			    								</xs:sequence>
			    							</xs:complexType>
    									
    									</xs:element>
    								</xs:sequence>
    							</xs:complexType>
    						</xs:element>
    					</xs:sequence>
    				</xs:complexType>
    			</xs:element>
    			<xs:element name="formats" minOccurs="1" maxOccurs="1">
    				<xs:complexType>
    					<xs:sequence>
    						<xs:element name="format" minOccurs="1" maxOccurs="unbounded">
    							<xs:complexType>
    								<xs:sequence>
			    						<xs:element name="mime-type" minOccurs="1" maxOccurs="unbounded">
			    							<xs:complexType>
			    								<xs:attribute name="id" type="xs:string" use="required"/>
			    							</xs:complexType>
			    						</xs:element>
			    					</xs:sequence>
    								<xs:attribute name="id" type="xs:QName" use="required"/>
    							</xs:complexType>
    						</xs:element>
    					</xs:sequence>
    				</xs:complexType>
    			</xs:element>
    			<xs:element name="config" minOccurs="1" maxOccurs="1">
    				<xs:complexType>
    					<xs:sequence>
    						<xs:element name="default-namespace" maxOccurs="unbounded">
    							<xs:complexType>
    								<xs:attribute name="uri" type="xs:anyURI" use="required"/>
    								<xs:attribute name="prefix" type="xs:QName" use="required"/>
    							</xs:complexType>
    						</xs:element>
    					</xs:sequence>
    				</xs:complexType>
    			</xs:element>
    		</xs:sequence>
    	</xs:complexType>
    </xs:element>

    <xs:complexType name="PredicateType">
    	<xs:sequence>
			<xs:element name="predicate" type="PredicateType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="value" type="xs:anyURI" use="required"/>
		<xs:attribute name="multiple" type="xs:boolean" default="false" use="optional"/>
		<xs:attribute name="mandatory" type="xs:boolean" default="false" use="optional"/>
		<xs:attribute name="localized" type="xs:boolean" default="false" use="optional"/>
		<xs:attribute name="searchable" type="xs:boolean" default="true" use="optional"/>
		<xs:attribute name="generateObject" type="xs:boolean" default="true" use="optional"/>
		
		<xs:attribute name="resourceModel" type="xs:NCName" use="optional"/>
		<!-- include linked resources for rdf export. If true, the linked resource is completely included. If false, an rdf:resource attribute with an url to the linked resource is created-->
		<xs:attribute name="includeResource" type="xs:boolean" use="optional"/>
		<xs:attribute name="default" type="xs:string" default="" use="optional"/>
		<xs:attribute name="overwrite" type="xs:boolean" use="optional"/>
		<xs:attribute name="event" type="EventType" use="optional"/>
		<xs:attribute name="modify" type="xs:boolean" default="true" use="optional"/>
		<xs:attribute name="restricted" type="xs:boolean" default="false" use="optional"/>
		<xs:attribute name="shouldBeUnique" type="xs:boolean" default="false" use="optional"/>
		<xs:attribute name="suggest-url" type="xs:string" use="optional"/>
		<xs:attribute name="suggest-response-handler" type="xs:string" use="optional"/>
		<xs:attribute name="suggest-request-handler" type="xs:string" use="optional"/>
		<xs:attribute name="type" type="xs:string" use="optional"/>
    </xs:complexType>
    
    <xs:simpleType name="EventType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="onload"/>
			<xs:enumeration value="onsave"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== MPDL/INGe/cone/src/main/resources/models.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 CDDL HEADER START

 The contents of this file are subject to the terms of the
 Common Development and Distribution License, Version 1.0 only
 (the "License"). You may not use this file except in compliance
 with the License.

 You can obtain a copy of the license at license/ESCIDOC.LICENSE
 or http://www.escidoc.org/license.
 See the License for the specific language governing permissions
 and limitations under the License.

 When distributing Covered Code, include this CDDL HEADER in each
 file and include the License file at license/ESCIDOC.LICENSE.
 If applicable, add the following below this CDDL HEADER, with the
 fields enclosed by brackets "[]" replaced with your own identifying
 information: Portions Copyright [yyyy] [name of copyright owner]

 CDDL HEADER END


 Copyright 2006-2012 Fachinformationszentrum Karlsruhe Gesellschaft
 für wissenschaftlich-technische Information mbH and Max-Planck-
 Gesellschaft zur Förderung der Wissenschaft e.V.
 All rights reserved. Use is subject to license terms.
-->
<models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="models.xsd">
	<model>
		<name>journals</name>
		<aliases>
			<alias>jnar</alias>
			<alias>journals</alias>
		</aliases>
		<description>Journal Names</description>
		<open>true</open>
		<primary-identifier control="false" subject-prefix="journals/resource/" generate-cone-id="false"></primary-identifier>
		<predicates>
			<predicate name="Journal Name" value="http://purl.org/dc/elements/1.1/title" multiple="false" mandatory="true" localized="false" searchable="true" shouldBeUnique="true"/>
			<predicate name="Alternative Journal Name" value="http://purl.org/dc/terms/alternative" multiple="true" mandatory="false" localized="false" searchable="true" shouldBeUnique="true"/>
			<predicate name="Abbreviation" value="http://purl.org/escidoc/metadata/terms/0.1/abbreviation" multiple="false" mandatory="false" localized="false" searchable="true" shouldBeUnique="true"/>
			<predicate name="Identifier" value="http://purl.org/dc/elements/1.1/identifier" multiple="true" mandatory="false" localized="false" generateObject="true" searchable="true">
				<predicate name="Value" value="http://www.w3.org/1999/02/22-rdf-syntax-ns#value" multiple="false" mandatory="true" localized="false" searchable="true" shouldBeUnique="true"/>
				<predicate name="ID Type" value="http://www.w3.org/2001/XMLSchema-instance type" multiple="false" mandatory="true" localized="false" searchable="false"/>
			</predicate>
			<predicate name="Publisher" value="http://purl.org/dc/elements/1.1/publisher" multiple="false" mandatory="false" localized="false" searchable="true"/>
			<predicate name="Publisher Place" value="http://purl.org/dc/terms/publisher" multiple="false" mandatory="false" localized="true" searchable="true"/>
			<predicate name="Citation Style" value="http://purl.org/escidoc/metadata/terms/0.1/citation-style" multiple="false" mandatory="false" localized="false" searchable="true"/>
		</predicates>
		<results>
			<result>
				<type>main</type>
				<result-pattern>
&lt;http://purl.org/dc/elements/1.1/title&gt;
OR{&lt;http://purl.org/dc/elements/1.1/publisher&gt;,&lt;http://purl.org/dc/terms/publisher&gt;}:;
&lt;http://purl.org/dc/elements/1.1/publisher&gt;
AND{&lt;http://purl.org/dc/elements/1.1/publisher&gt;,&lt;http://purl.org/dc/terms/publisher&gt;}:,
&lt;http://purl.org/dc/terms/publisher&gt;
				</result-pattern>
				<sort-pattern>
&lt;http://purl.org/dc/elements/1.1/title&gt;
OR{&lt;http://purl.org/dc/elements/1.1/publisher&gt;,&lt;http://purl.org/dc/terms/publisher&gt;}:;
&lt;http://purl.org/dc/elements/1.1/publisher&gt;
AND{&lt;http://purl.org/dc/elements/1.1/publisher&gt;,&lt;http://purl.org/dc/terms/publisher&gt;}:,
&lt;http://purl.org/dc/terms/publisher&gt;
				</sort-pattern>
			</result>
			<result>
				<type>alt</type>
				<result-pattern>
&lt;http://purl.org/escidoc/metadata/terms/0.1/abbreviation&gt;
AND{&lt;http://purl.org/escidoc/metadata/terms/0.1/abbreviation&gt;,OR{&lt;http://purl.org/dc/elements/1.1/publisher&gt;,&lt;http://purl.org/dc/terms/publisher&gt;}}:;
&lt;http://purl.org/escidoc/metadata/terms/0.1/abbreviation&gt;:&lt;http://purl.org/dc/elements/1.1/publisher&gt;
AND{&lt;http://purl.org/escidoc/metadata/terms/0.1/abbreviation&gt;,&lt;http://purl.org/dc/elements/1.1/publisher&gt;,&lt;http://purl.org/dc/terms/publisher&gt;}:,
&lt;http://purl.org/escidoc/metadata/terms/0.1/abbreviation&gt;:&lt;http://purl.org/dc/terms/publisher&gt;
				</result-pattern>
				<sort-pattern>
&lt;http://purl.org/dc/elements/1.1/title&gt;
OR{&lt;http://purl.org/dc/elements/1.1/publisher&gt;,&lt;http://purl.org/dc/terms/publisher&gt;}:;
&lt;http://purl.org/dc/elements/1.1/publisher&gt;
AND{&lt;http://purl.org/dc/elements/1.1/publisher&gt;,&lt;http://purl.org/dc/terms/publisher&gt;}:,
&lt;http://purl.org/dc/terms/publisher&gt;
 &lt;http://purl.org/escidoc/metadata/terms/0.1/abbreviation&gt;
 				</sort-pattern>
			</result>
			<result>
				<type>alt</type>
				<result-pattern>
&lt;http://purl.org/dc/terms/alternative&gt;
AND{&lt;http://purl.org/dc/terms/alternative&gt;,OR{&lt;http://purl.org/dc/elements/1.1/publisher&gt;,&lt;http://purl.org/dc/terms/publisher&gt;}}:;
&lt;http://purl.org/dc/terms/alternative&gt;:&lt;http://purl.org/dc/elements/1.1/publisher&gt;
AND{&lt;http://purl.org/dc/terms/alternative&gt;,&lt;http://purl.org/dc/elements/1.1/publisher&gt;,&lt;http://purl.org/dc/terms/publisher&gt;}:,
&lt;http://purl.org/dc/terms/alternative&gt;:&lt;http://purl.org/dc/terms/publisher&gt;
				</result-pattern>
				<sort-pattern>
&lt;http://purl.org/dc/elements/1.1/title&gt;
OR{&lt;http://purl.org/dc/elements/1.1/publisher&gt;,&lt;http://purl.org/dc/terms/publisher&gt;}:;
&lt;http://purl.org/dc/elements/1.1/publisher&gt;
AND{&lt;http://purl.org/dc/elements/1.1/publisher&gt;,&lt;http://purl.org/dc/terms/publisher&gt;}:,
&lt;http://purl.org/dc/terms/publisher&gt;
 &lt;http://purl.org/dc/terms/alternative&gt;
 				</sort-pattern>
			</result>
		</results>
	</model>

	<model>
		<name>iso639-1</name>
		<aliases>
			<alias>iso639-1</alias>
		</aliases>
		<description>Languages</description>
		<open>false</open>
		<primary-identifier control="true" subject-prefix="iso639-1/resource/" generate-cone-id="false">http://purl.org/dc/elements/1.1/identifier</primary-identifier>
		<predicates>
			<predicate name="ISO639-3 Relation" value="http://purl.org/dc/elements/1.1/relation" multiple="false" mandatory="true" localized="false" searchable="true" generateObject="false" resourceModel="iso639-3" shouldBeUnique="true"/>
			<predicate name="ISO639 Code" value="http://purl.org/dc/elements/1.1/identifier" multiple="false" mandatory="true" localized="false" searchable="true" shouldBeUnique="true"/>
		</predicates>
		<results>
			<result>
				<result-pattern>
&lt;http://purl.org/dc/elements/1.1/identifier&gt;
 -
&lt;http://purl.org/dc/elements/1.1/relation|http://purl.org/dc/elements/1.1/title&gt;
					</result-pattern>

			</result>
		</results>
	</model>

	<model>
		<name>iso639-2</name>
		<aliases>
			<alias>iso639-2</alias>
		</aliases>
		<description>Languages</description>
		<open>false</open>
		<primary-identifier control="true" subject-prefix="iso639-2/resource/" generate-cone-id="false">http://purl.org/dc/elements/1.1/identifier</primary-identifier>
		<predicates>
			<predicate name="ISO639-3 Relation" value="http://purl.org/dc/elements/1.1/relation" multiple="false" mandatory="false" localized="false" searchable="true" generateObject="false" resourceModel="iso639-3" shouldBeUnique="true"/>
			<predicate name="ISO639 Code" value="http://purl.org/dc/elements/1.1/identifier" multiple="false" mandatory="true" localized="false" searchable="true" shouldBeUnique="true"/>
			<predicate name="Name" value="http://purl.org/dc/elements/1.1/title" multiple="false" mandatory="false" localized="true" searchable="true" shouldBeUnique="true"/>
		</predicates>
		<results>
			<result>
				<result-pattern>
&lt;http://purl.org/dc/elements/1.1/identifier&gt;
AND{&lt;http://purl.org/dc/elements/1.1/identifier&gt;,&lt;http://purl.org/dc/elements/1.1/relation|http://purl.org/dc/elements/1.1/identifier&gt;}: /
&lt;http://purl.org/dc/elements/1.1/relation|http://purl.org/dc/elements/1.1/identifier&gt;
 -
&lt;http://purl.org/dc/elements/1.1/title&gt;
NOT{&lt;http://purl.org/dc/elements/1.1/title&gt;}:&lt;http://purl.org/dc/elements/1.1/relation|http://purl.org/dc/elements/1.1/title&gt;
					</result-pattern>

			</result>
		</results>
	</model>

	<model>
		<name>iso639-3</name>
		<aliases>
			<alias>iso639-3</alias>
		</aliases>
		<description>Languages</description>
		<open>false</open>
		<primary-identifier control="true" subject-prefix="iso639-3/resource/" generate-cone-id="false">http://purl.org/dc/elements/1.1/identifier</primary-identifier>
		<predicates>
			<predicate name="Name" value="http://purl.org/dc/elements/1.1/title" multiple="false" mandatory="true" localized="true" searchable="true" shouldBeUnique="true"/>
			<predicate name="ISO639 Code" value="http://purl.org/dc/elements/1.1/identifier" multiple="false" mandatory="true" localized="false" searchable="true" shouldBeUnique="true"/>
			<predicate name="Geo location" value="http://earth.google.com/kml/2.1 coordinates" multiple="false" localized="false" searchable="true" mandatory="false"/>
		</predicates>
		<results>
			<result>
				<result-pattern>
&lt;http://purl.org/dc/elements/1.1/identifier&gt;
 -
&lt;http://purl.org/dc/elements/1.1/title&gt;
				</result-pattern>
			</result>
		</results>
	</model>

	<model>
		<name>persons</name>
		<aliases>
			<alias>authors</alias>
			<alias>persons</alias>
		</aliases>
		<description>Persons</description>
		<open>true</open>
		<primary-identifier control="false" generate-cone-id="true"/>
		<predicates>
